# _*_ coding：utf-8 _*_
# @Time     : 2022/4/28 11:38
# @Author   : WPH
# @File     : desired_caps.yml.py
# @Software : PyCharm

automationName: uiautomator2
platformVersion: 7.1.2
platformName: Android
appPackage: com.netease.newsreader.activity
appActivity: com.netease.nr.phone.main.MainActivity
noReset: True
ip: "127.0.0.1"
